## Importing package

In [2]:
import numpy as np

## Creating Arrays

In [3]:
arr1 = np.array([1,2,3,4,5,6])
print("1D array: ", arr1)
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array: ", "\n",arr2)

1D array:  [1 2 3 4 5 6]
2D array:  
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Understanding attributes of arrays

In [4]:
print("About arr2:")
print("Type\t\t:" ,type(arr2))
print("Datatype\t:",arr2.dtype)
print("Shape\t\t:", arr2.shape)
print("Size\t\t:",arr2.size)
print("itemsize\t:",arr2.itemsize)
print("No. of dim\t:",arr2.ndim)
print("No. of bytes\t:", arr2.nbytes)

About arr2:
Type		: <class 'numpy.ndarray'>
Datatype	: int64
Shape		: (3, 3)
Size		: 9
itemsize	: 8
No. of dim	: 2
No. of bytes	: 72


## Creating Special arrays

In [5]:
arr3 = np.zeros((5,2), dtype=int)
arr4 = np.ones((3,4),dtype=float)
arr5 = np.eye(4,3)
arr6 = np.random.rand(3,2)
arr7 = np.random.randint(7,size=(2,6))
print("Zero Array \t:\n",arr3)
print("Arrays with unit values\t:\n",arr4)
print("Identity matrix\t:\n",arr5)
print("Random array\t\n",arr6)
print("Random integer array\t:\n" , arr7)

Zero Array 	:
 [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
Arrays with unit values	:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix	:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Random array	
 [[0.57662832 0.13295862]
 [0.80039028 0.21484504]
 [0.36590037 0.97644292]]
Random integer array	:
 [[0 6 5 5 1 0]
 [3 0 4 4 1 3]]


<h2>Creating arrays using arange</h2>

In [9]:
arr8 = np.arange(1,10,2)
print("Array created with arange: \t\n",arr8)
arr8 = np.arange(1,10)
print("Array createed with arange:\n",arr8)
arr8=np.arange(10)
print("range print\n",arr8)

Array created with arange: 	
 [1 3 5 7 9]
Array createed with arange:
 [1 2 3 4 5 6 7 8 9]
range print
 [0 1 2 3 4 5 6 7 8 9]


## Creating arrays using "linspace"
linspace creates an array within the range.
    Number of elements to be created is fixed and the interval between the elements is calculated by the system.
    linspace will include the last value(stop)

In [10]:
arr9 = np.linspace(1,5,50)
print("Array created using linspace requesting 50 elements within 1 to 10:\t\n",arr9)

Array created using linspace requesting 50 elements within 1 to 10:	
 [1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [11]:
arr10 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr10)
print("Row 2:",arr10[1,:])
print("Column 2:",arr10[:,3])
print("Elements 7,8,12,13 :\n", arr10[1:3,1:3])
print("All elements: \n",arr10[::])
print("Strides:\n",arr10[0::2,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row 2: [ 6  7  8  9 10]
Column 2: [ 4  9 14 19]
Elements 7,8,12,13 :
 [[ 7  8]
 [12 13]]
All elements: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Strides:
 [[ 2  3]
 [12 13]]


## Masking - Important concept in Image processing

In [12]:
arr11 = np.array([1,2,3,4,5,6,7,8,9])
mask = np.array([0,1,1,0,1,0,1,0,0],dtype=bool)
print(arr11[mask])

[2 3 5 7]


In [14]:
maskarray=np.array([0,0,1,1,0])
mask=np.array(maskarray,dtype=bool)
array=np.array([1,2,3,4,5])
print(array[mask])

[3 4]


In [28]:
arr12 = np.array([[1,2,3,4,5],[6,7,8,9,9]])
print(arr12)
print("Sum  \t\t:",np.sum(arr12))
print("Sum_with_axis \t:",np.sum(arr12,axis=0))
print("Prod \t\t:",np.prod(arr12))
print("Prod_with_axis  :",np.prod(arr12,axis=0))
print("Minimum  \t:",np.min(arr12,axis=0))
print("Maximum  \t:",np.max(arr12,axis=0))
print("Minimum_with_axis:",np.min(arr12,axis=1))
print("Maximum_with_axis:",np.max(arr12,axis=1))
print("Mean  \t\t:",np.mean(arr12,axis=0))
print("mean_horizontal:",np.mean(arr12,axis=1))
print("Variance \t:",np.var(arr12,axis=0))
print("Variance_horizontal:",np.var(arr12,axis=1))
print("Standard Deviation:",np.std(arr12,axis=0))
print("Average  \t:",np.average(arr12,axis=0))
print("Weighted Average :",np.average(arr12,weights=[1,2,3,4,5],axis=1))

[[1 2 3 4 5]
 [6 7 8 9 9]]
Sum  		: 54
Sum_with_axis 	: [ 7  9 11 13 14]
Prod 		: 3265920
Prod_with_axis  : [ 6 14 24 36 45]
Minimum  	: [1 2 3 4 5]
Maximum  	: [6 7 8 9 9]
Minimum_with_axis: [1 6]
Maximum_with_axis: [5 9]
Mean  		: [3.5 4.5 5.5 6.5 7. ]
mean_horizontal: [3.  7.8]
Variance 	: [6.25 6.25 6.25 6.25 4.  ]
Variance_horizontal: [2.   1.36]
Standard Deviation: [2.5 2.5 2.5 2.5 2. ]
Average  	: [3.5 4.5 5.5 6.5 7. ]
Weighted Average : [3.66666667 8.33333333]


## Scalar Operations - Arithmetic

In [29]:
arr13 = np.array([1,2,3])
arr14 = np.array([4,5,6])
arr15 = arr13+arr14
arr16 = arr13 - arr14
print("Summation:\t",arr15)
print("Difference:\t",arr16)

arr16+=5
print("Previous output after adding 5:",arr16)

###  Try other operations



Summation:	 [5 7 9]
Difference:	 [-3 -3 -3]
Previous output after adding 5: [2 2 2]


## Relational Operations

In [31]:
result1 = arr16 == arr15
print(result1)
print("it is checking elementwise.")

[False False False]
it is checking elementwise.


<h2>## Trignometric & Logarithmic operations</h2>

In [32]:
arr17 = np.array([15,30,45,90])
result7 = np.sin(arr17)
print("Sin values:\t",result7)
result8 = np.log(arr17)
print("Log value:\t",result8)

### Try other operations

Sin values:	 [ 0.65028784 -0.98803162  0.85090352  0.89399666]
Log value:	 [2.7080502  3.40119738 3.80666249 4.49980967]


## Vector operations

### Math - Scalar and Vector

#### Scalar

* np.add(a,1) -> Add 1 to each array element
* np.subtract(a,2) -> Subtract 2 from each array element
* np.multiply(a,3) -> Multiply each array element by 3
* np.divide(a,4) -> Divide each array element by 4 (it returns np.nan for division by zero)
* np.power(a,5) -> Raise each array element to the 5th power

#### Vector Math

* np.add(a1,a2) -> Elementwise add a2 to a1
* np.subtract(a1,a2) -> Elementwise subtract a2 from a1
* np.multiply(a1,a2) -> Elementwise multiply a1 by a2
* np.divide(a1,a2) -> Elementwise divide a1 by a2
* np.power(a1,a2) -> Elementwise raise a1 raised to the power of a2

* np.array_equal(a1,a2) -> Returns True if the arrays have the same elements and shape *(Note - a1 == a2 -> Returns True if the arrays have the same elements)*
* np.sqrt(a) -> Square root of each element in the array
* np.round(a) -> Rounds to the nearest int

In [42]:
print("scalar math")
a=np.arange(5)
print("array is:",a)
print("add\t:",np.add(a,1))
print("subtract :",np.subtract(a,2))
print("multiply :",np.multiply(a,3))
print("divide\t:",np.divide(a,4))
print("power\t:",np.power(a,5))
print("\nVector math")
b=np.arange(1,10,2)
print("arrays are:",a,b)
print("add\t:",np.add(a,b))
print("subtract :",np.subtract(a,b))
print("multiply :",np.multiply(a,b))
print("divide \t:",np.divide(a,b))

scalar math
array is: [0 1 2 3 4]
add	: [1 2 3 4 5]
subtract : [-2 -1  0  1  2]
multiply : [ 0  3  6  9 12]
divide	: [0.   0.25 0.5  0.75 1.  ]
power	: [   0    1   32  243 1024]

Vector math
arrays are: [0 1 2 3 4] [1 3 5 7 9]
add	: [ 1  4  7 10 13]
subtract : [-1 -2 -3 -4 -5]
multiply : [ 0  3 10 21 36]
divide 	: [0.         0.33333333 0.4        0.42857143 0.44444444]


### Statistical Analysis

* np.mean(a) -> Returns mean along specific axis
* np.sum(a) -> Returns sum of all values in a
* a.min() -> Returns minimum value of a
* a.max() -> Returns maximum value of specific axis
* np.var(a)
* np.std(a)
* arr.corrcoef()

In [44]:
print("mean of a",np.mean(a))
print("sum of a :",np.sum(a))
print("min of a :",np.min(a))
print("max of a :",np.max(a))
print("variance of a :",np.var(a))
print("standard_diviation of a:",np.std(a))
print("correlation coef:",np.corrcoef(a))

mean of a 2.0
sum of a : 10
min of a : 0
max of a : 4
variance of a : 2.0
standard_diviation of a: 1.4142135623730951
correlation coef: 1.0


1. sum_value = np.sum(a)
2. columnSum = np.sum(a, axis = 0)
3. rowSum = np.sum(a, axis = 1)

In [51]:
print(a)
c=[a,b]
print(c)
sum_value=np.sum(c)
column_sum=np.sum(c,axis=0)
row_sum=np.sum(c,axis=1)
print("sum_value\t:",sum_value,"\ncolumn_sum\t:",column_sum)
print("row_sum\t:",row_sum)

[0 1 2 3 4]
[array([0, 1, 2, 3, 4]), array([1, 3, 5, 7, 9])]
sum_value	: 35 
column_sum	: [ 1  4  7 10 13]
row_sum	: [10 25]
